### ISSUE TITLE
Pickupable Vehicles

### ISSUE THREAD

**Issue by acmgit** [APercy/automobiles_pck#22]
Would be a nice feature, when the player can pickup his vehicle and replace in another place.
Now i have only seen the option to destroy the vehicle.

**Comment by APercy** [comment]
Was intentional, but I'll think to add it as an option configurable by the server owner

**Comment by acmgit** [comment]
Of course, would be a solution.

**Comment by acmgit** [comment]
I've made an update, but when i try to pickup the car (with punching), it destroys again.
What is the remove-code now doing?
