### ISSUE TITLE
Reverse Thrusters

### ISSUE THREAD

**Issue by DustyDave961** [APercy/automobiles_pck#25]
For the love of God, PLEASE make it possible for vehicles to go in reverse with the S key. I couldn't figure out how to go backwards and thought it was impossible until DustyBagel told me to press Shift. I had to destroy a lot of vehicles before that because I couldn't get unstuck.

**Comment by APercy** [comment]
S is for the brakes :)
Just hold Shift (Sneak) to go reverse. I planned a manual transmission that will use shift and jump to change it, but it is for the future ;)
