### ISSUE TITLE
Lost Inventory

### ISSUE THREAD

**Issue by DustyDave961** [APercy/automobiles_pck#26]
DustyBagel just accidentally destroyed their white van full of desert stone and lost all of it. Please make vehicles drop their inventory contents when they're destroyed so people don't lose their stuff.

**Comment by APercy** [comment]
Originally it was possible, but unfortunately a terrible problem occurred: When destroying the vehicle, so many entities were created that the server crashed, so I limited it to 5 items per slot only.

**Comment by DustyDave961** [comment]
I see. That makes sense. I'm kind of surprised it's not a setting for servers that can handle it.
