### ISSUE TITLE
Allow driving up one node high slope

### ISSUE THREAD

**Issue by MrRar** [APercy/automobiles_pck#4]
Allow driving up one node high slope. No doubt not allowing this was intentional. After all, this is realistic. There aren't many cars that can drive up a 1 meter high block. It would be nice to have a setting that allows this so you can drive cars off road.

**Comment by APercy** [comment]
Thank you, but the tilt code will become unstable and useless.. So for this time: [https://br.pinterest.com/pin/497647827550995581/](url)

**Comment by MrRar** [comment]
@APercy I tried setting the step hight to 1.1 on all the vehicles and it worked OK. It got stuck sometimes. I think it would be nice to have a setting that is off by default to set them all to 1.1

**Comment by APercy** [comment]
Done. Use the command /noobfy_the_vehicles true/false
Then restart the server or game

**Comment by MrRar** [comment]
> Done. Use the command /noobfy_the_vehicles true/false Then restart the server or game

That's nice although I think it would be better to implement a Minetest setting instead of a command.
